#!/usr/bin/env python3
"""
Count hand-written C++ code lines in a project.
Excludes:
- Auto-generated files
- Third-party/vendor code
- Build directories
- Comments and blank lines (optional)
"""

import os
import argparse
from pathlib import Path

# Directories to exclude
EXCLUDE_DIRS = {
    'build', 'third_party', 'vendor', 'external', 'deps',
    '.git', '.cache', 'cmake-build-*', 'out', 'bin', 'obj'
}

# Files to exclude (auto-generated)
EXCLUDE_FILES = {
    'moc_*.cpp', 'ui_*.h', 'qrc_*.cpp'  # Qt auto-generated
}

# C++ file extensions
CPP_EXTENSIONS = {'.cpp', '.cxx', '.cc', '.c++', '.h', '.hpp', '.hxx', '.h++'}

# Patterns for auto-generated files
AUTO_GENERATED_MARKERS = [
    '// Auto-generated',
    '// Generated by',
    '// This file was generated',
    '// DO NOT EDIT',
    '// DO NOT MODIFY'
]


def is_auto_generated(filepath):
    """Check if file contains auto-generated markers."""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            for i, line in enumerate(f):
                if i > 20:  # Check first 20 lines only
                    break
                if any(marker in line for marker in AUTO_GENERATED_MARKERS):
                    return True
    except Exception:
        pass
    return False


def count_lines_in_file(filepath, exclude_comments=False):
    """Count lines in a C++ file, optionally excluding comments."""
    total_lines = 0
    code_lines = 0
    comment_lines = 0
    blank_lines = 0
    in_block_comment = False

    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            for line in f:
                total_lines += 1
                stripped = line.strip()

                # Blank line
                if not stripped:
                    blank_lines += 1
                    continue

                # Handle block comments
                if in_block_comment:
                    comment_lines += 1
                    if '*/' in stripped:
                        in_block_comment = False
                    continue

                # Single-line comment
                if stripped.startswith('//'):
                    comment_lines += 1
                    continue

                # Block comment start
                if stripped.startswith('/*'):
                    comment_lines += 1
                    if '*/' not in stripped:
                        in_block_comment = True
                    continue

                # Count as code line
                code_lines += 1

    except Exception as e:
        print(f"  Warning: Could not read {filepath}: {e}")

    return {
        'total': total_lines,
        'code': code_lines,
        'comments': comment_lines,
        'blanks': blank_lines
    }


def should_exclude_file(filepath):
    """Check if file should be excluded based on name patterns."""
    filename = os.path.basename(filepath)
    for pattern in EXCLUDE_FILES:
        if pattern.endswith('*'):
            if filename.startswith(pattern[:-1]):
                return True
        else:
            if filename == pattern:
                return True
    return False


def count_cpp_code(root_dir, exclude_comments=False):
    """Walk directory tree and count C++ code lines."""
    root_path = Path(root_dir)
    if not root_path.exists():
        print(f"Error: Directory '{root_dir}' does not exist.")
        return

    # Only scan src/ and include/ directories
    scan_dirs = [root_path / 'src', root_path / 'include']
    scan_dirs = [d for d in scan_dirs if d.exists()]

    if not scan_dirs:
        print(f"Error: Neither 'src/' nor 'include/' found in '{root_dir}'.")
        return

    stats = {
        'total_files': 0,
        'total_lines': 0,
        'code_lines': 0,
        'comment_lines': 0,
        'blank_lines': 0,
        'auto_generated_excluded': 0,
        'files': []
    }

    for scan_root in scan_dirs:
        for dirpath, dirnames, filenames in os.walk(scan_root):
            # Exclude directories
            dirnames[:] = [
                d for d in dirnames
                if d not in EXCLUDE_DIRS and not d.startswith('.')
            ]

            for filename in sorted(filenames):
                filepath = os.path.join(dirpath, filename)
                ext = os.path.splitext(filename)[1]

                if ext not in CPP_EXTENSIONS:
                    continue

                if should_exclude_file(filepath):
                    continue

                if is_auto_generated(filepath):
                    stats['auto_generated_excluded'] += 1
                    continue

                file_stats = count_lines_in_file(filepath, exclude_comments)
                if file_stats['total'] > 0:
                    rel_path = os.path.relpath(filepath, root_dir)

                    stats['total_files'] += 1
                    stats['total_lines'] += file_stats['total']
                    stats['code_lines'] += file_stats['code']
                    stats['comment_lines'] += file_stats['comments']
                    stats['blank_lines'] += file_stats['blanks']

                    stats['files'].append({
                        'path': rel_path,
                        'code': file_stats['code'],
                        'comments': file_stats['comments'],
                        'blanks': file_stats['blanks'],
                        'total': file_stats['total']
                    })

    return stats


def print_stats(stats, exclude_comments=False):
    """Print formatted statistics."""
    print("\n" + "=" * 80)
    print("C++ Code Statistics")
    print("=" * 80)

    # Sort files by code lines (descending)
    sorted_files = sorted(stats['files'], key=lambda x: x['code'], reverse=True)

    print(f"\n{'File':<60} {'Code':>6} {'Comments':>9} {'Blanks':>7} {'Total':>6}")
    print("-" * 90)

    for file_info in sorted_files:
        print(f"{file_info['path']:<60} {file_info['code']:>6} {file_info['comments']:>9} {file_info['blanks']:>7} {file_info['total']:>6}")

    print("-" * 90)

    print(f"\nHand-written C++ Code (src/ + include/):")
    print(f"  Files:                   {stats['total_files']}")
    print(f"  Total lines:             {stats['total_lines']}")
    print(f"  Code lines:              {stats['code_lines']}")
    print(f"  Comment lines:           {stats['comment_lines']}")
    print(f"  Blank lines:             {stats['blank_lines']}")

    if stats['total_lines'] > 0:
        print(f"\n  Code percentage:         {stats['code_lines']/stats['total_lines']*100:.1f}%")
        print(f"  Comment percentage:      {stats['comment_lines']/stats['total_lines']*100:.1f}%")

    print("=" * 80 + "\n")


def main():
    parser = argparse.ArgumentParser(
        description='Count hand-written C++ code lines in a project'
    )
    parser.add_argument(
        'directory',
        nargs='?',
        default='.',
        help='Root directory to scan (default: current directory)'
    )
    parser.add_argument(
        '--exclude-comments',
        action='store_true',
        help='Exclude comments from code line count'
    )
    parser.add_argument(
        '--summary-only',
        action='store_true',
        help='Show only summary, not individual files'
    )

    args = parser.parse_args()

    stats = count_cpp_code(args.directory, args.exclude_comments)

    if stats:
        if args.summary_only:
            print(f"\nHand-written C++ code lines:     {stats['code_lines']}")
            print(f"Comment lines:                   {stats['comment_lines']}")
            print(f"Total files:                     {stats['total_files']}\n")
        else:
            print_stats(stats, args.exclude_comments)


if __name__ == '__main__':
    main()
