const range=(n,pre,side,type,start=0)=>Array.from({length:n},(_,i)=>({id:`${pre}${start+i}`,side,type}));
export const COMPONENTS = {
  atmega328p:{ label:'ATmega328P', category:'MCU', color:'#8b5cf6',
    properties:[{id:'binary',label:'Hex File Path',type:'text',default:'tests/blink.hex'},
                {id:'f_cpu',label:'Frequency (Hz)',type:'number',default:16000000},
                {id:'vref',label:'VRef (V)',type:'number',default:5.0}],
    pins:[{id:'AREF',side:'left',type:'analog'},{id:'AVCC',side:'left',type:'power'},
          {id:'GND',side:'left',type:'power'},{id:'VCC',side:'left',type:'power'},
          {id:'ADC6',side:'right',type:'io'},{id:'ADC7',side:'right',type:'io'},
          ...range(8,'PB','right','io'),...range(7,'PC','right','io'),...range(8,'PD','right','io')] },
  led:{ label:'LED', category:'Output', color:'#ef4444',
    properties:[{id:'color',label:'Color',type:'text',default:'#ff0000'},{id:'v_f',label:'Forward V (V)',type:'number',default:2.0}],
    pins:[{id:'A',side:'left',type:'power'},{id:'K',side:'right',type:'power'}] },
  seven_seg:{ label:'7-Segment Display', category:'Display', color:'#f87171',
    properties:[{id:'common',label:'Common',type:'text',default:'Cathode'}],
    pins:[{id:'A',side:'left',type:'io'},{id:'B',side:'left',type:'io'},{id:'C',side:'left',type:'io'},
          {id:'D',side:'left',type:'io'},{id:'COM',side:'left',type:'power'},
          {id:'E',side:'right',type:'io'},{id:'F',side:'right',type:'io'},{id:'G',side:'right',type:'io'},{id:'DP',side:'right',type:'io'}] },
  lcd_glass:{ label:'LCD Glass (4-Digit)', category:'Display', color:'#9db894',
    properties:[{id:'com_count',label:'Commons',type:'number',default:4}],
    pins:[...range(16,'SEG','left','io'),...range(4,'COM','right','power')] },
  button:{ label:'Push Button', category:'Input', color:'#38bdf8', properties:[],
    pins:[{id:'1',side:'left',type:'io'},{id:'2',side:'right',type:'io'}] },
  res:{ label:'Resistor', category:'Passive', color:'#f59e0b',
    properties:[{id:'value',label:'Resistance (Ω)',type:'text',default:'10k'}],
    pins:[{id:'1',side:'left',type:'io'},{id:'2',side:'right',type:'io'}] },
  vsrc:{ label:'V-Source', category:'Source', color:'#10b981',
    properties:[{id:'voltage',label:'Voltage (V)',type:'number',default:5.0}],
    pins:[{id:'+',side:'left',type:'power'},{id:'-',side:'right',type:'power'}] },
  gnd:{ label:'GND', category:'Power', color:'#94a3b8', properties:[],
    pins:[{id:'GND',side:'left',type:'power'}] },
  motor_dc:{ label:'DC Motor', category:'Actuator', color:'#a1a1aa',
    properties:[{id:'v_nom',label:'Nominal V (V)',type:'number',default:5.0}],
    pins:[{id:'+',side:'left',type:'power'},{id:'-',side:'right',type:'power'}] },
  eusart_terminal:{ label:'EUSART Terminal', category:'Instrument', color:'#0ea5e9',
    properties:[{id:'baud',label:'Baud Rate',type:'number',default:9600}],
    pins:[{id:'RX',side:'left',type:'io'},{id:'TX',side:'right',type:'io'}] },
  logic_analyzer:{ label:'Logic Analyzer 8CH', category:'Instrument', color:'#22c55e',
    properties:[{id:'sample_rate',label:'Sample Rate (MHz)',type:'number',default:24}],
    pins:[...range(8,'CH','left','io'),{id:'GND',side:'right',type:'power'},{id:'CLK',side:'right',type:'ctrl'}] },
  dac_monitor:{ label:'DAC Monitor', category:'Instrument', color:'#4ade80',
    properties:[{id:'range',label:'Voltage Range',type:'text',default:'0-5V'}],
    pins:[{id:'IN',side:'left',type:'analog'},{id:'REF',side:'left',type:'power'}] },
};
export const getComponent = t=>COMPONENTS[t]?{type:t,...COMPONENTS[t]}:null;
export const getAllComponents = ()=>Object.entries(COMPONENTS).map(([type,d])=>({type,...d}));
