#!/usr/bin/env python3
import xml.etree.ElementTree as ET
import sys
import os
import json

def parse_atdf(file_path, preferred_pinout=None):
    tree = ET.parse(file_path)
    root = tree.getroot()
    
    device_node = root.find('.//device')
    device_name = device_node.get('name')
    
    pinouts = root.find('.//pinouts')
    if pinouts is None:
        print(f"Error: No pinouts found in {file_path}")
        return None
        
    # Pick the pinout
    pinout = None
    if preferred_pinout:
        pinout = pinouts.find(f".//pinout[@name='{preferred_pinout}']")
    
    if pinout is None:
        # Just pick the one with the most pins (usually TQFP)
        pinouts_list = pinouts.findall('pinout')
        pinout = max(pinouts_list, key=lambda x: len(x.findall('pin')))
    
    pinout_name = pinout.get('name')
    print(f"// Generated from {device_name} ({pinout_name})", file=sys.stderr)
    
    pins_data = []
    
    # Heuristic for pin categorization
    for pin_node in pinout.findall('pin'):
        pad = pin_node.get('pad')
        num = pin_node.get('number')
        
        pin_type = 'io'
        if 'VCC' in pad or 'VDD' in pad: pin_type = 'power'
        elif 'GND' in pad or 'VSS' in pad: pin_type = 'power'
        elif 'RESET' in pad: pin_type = 'ctrl'
        elif 'XTAL' in pad: pin_type = 'osc'
        elif 'AREF' in pad or 'AVCC' in pad: pin_type = 'analog'
        
        # Determine side
        # System pins usually on the left, IO on the right
        side = 'right'
        if pin_type in ['power', 'ctrl', 'osc', 'analog']:
            side = 'left'
            
        pins_data.append({
            'id': pad,
            'side': side,
            'type': pin_type
        })
        
    # Sort pins: System pins first, then IO pins alphabetical
    left_pins = sorted([p for p in pins_data if p['side'] == 'left'], key=lambda x: x['id'])
    right_pins = sorted([p for p in pins_data if p['side'] == 'right'], key=lambda x: x['id'])
    
    component = {
        'type_id': device_name.lower().replace('-', '_'),
        'label': device_name,
        'category': 'MCU',
        'color': 'var(--primary)',
        'properties': [
            { 'id': 'binary', 'label': 'Hex File Path', 'type': 'text', 'default': f'{device_name.lower()}.hex' },
            { 'id': 'f_cpu',  'label': 'Frequency (Hz)', 'type': 'number', 'default': 16000000 },
            { 'id': 'vref',   'label': 'VRef (V)',       'type': 'number', 'default': 5.0 }
        ],
        'pins': left_pins + right_pins
    }
    
    return component

def format_as_js(data):
    # Custom formatter to make it look like the existing code
    lines = []
    lines.append(f"  {data['type_id']}: {{")
    lines.append(f"    label: '{data['label']}',")
    lines.append(f"    category: '{data['category']}',")
    lines.append(f"    color: '{data['color']}',")
    
    # Properties
    lines.append(f"    properties: {json.dumps(data['properties'], indent=6)},")
    
    # Pins
    lines.append(f"    pins: [")
    for p in data['pins']:
        lines.append(f"      {{ id: '{p['id']}', side: '{p['side']}', type: '{p['type']}' }},")
    lines.append(f"    ],")
    lines.append(f"  }},")
    
    return "\n".join(lines)

def format_as_json(data):
    return data

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Generate component definitions from ATDF files.")
    parser.add_argument("path", help="Path to ATDF file or directory")
    parser.add_argument("--pinout", help="Preferred pinout name")
    parser.add_argument("--output", help="Output JSON file", default=None)
    
    args = parser.parse_args()
    
    all_components = {}
    
    if os.path.isdir(args.path):
        for f in os.listdir(args.path):
            if f.endswith(".atdf"):
                print(f"Processing {f}...", file=sys.stderr)
                comp = parse_atdf(os.path.join(args.path, f), args.pinout)
                if comp:
                    all_components[comp['type_id']] = comp
    else:
        comp = parse_atdf(args.path, args.pinout)
        if comp:
            all_components[comp['type_id']] = comp
            
    if args.output:
        is_js = args.output.endswith('.js')
        with open(args.output, 'w') as f:
            if is_js:
                f.write("/** Auto-generated by gen_chip_component.py **/\n")
                f.write("export const DYNAMIC_MCUS = ")
            json.dump(all_components, f, indent=2)
            if is_js:
                f.write(";\n")
        print(f"Saved {len(all_components)} components to {args.output}", file=sys.stderr)
    else:
        # If single file and no output specified, print as JS block for convenience
        if len(all_components) == 1:
            print(format_as_js(list(all_components.values())[0]))
        else:
            print(json.dumps(all_components, indent=2))
