#pragma once
#include "vioavr/core/device.hpp"

namespace vioavr::core::devices {

inline constexpr DeviceDescriptor atxmega8e5 {
    .name = "ATxmega8E5",
    .flash_words = 6144U,
    .sram_bytes = 1024U,
    .sram_start = 0x2000U,
    .eeprom_bytes = 512U,
    .interrupt_vector_count = 41U,
    .interrupt_vector_size = 4U,
    .flash_page_size = 0x128U,
    .register_file_range = { 0x0000, 0x001F },
    .io_range = { 0x0000, 0x003F },
    .extended_io_range = { 0x0040, 0x0FFF },
    .mapped_eeprom = { 0x1000U, 0x0200U },

    .spl_address = 0x3DU,
    .sph_address = 0x3EU,
    .sreg_address = 0x3FU,
    .rampz_address = 0x3BU,
    .eind_address = 0x3CU,
    .prr_address = 112U,
    .ccp_address = 0x34U,
    .cpu_frequency_hz = 32'000'000U,

    .adc_xmega_count = 1U,
    .adcs_xmega = {{
        {
            .ctrla_address = 512U,
            .ctrlb_address = 513U,
            .refctrl_address = 514U,
            .evctrl_address = 515U,
            .prescaler_address = 516U,
            .intflags_address = 515U,
            .temp_address = 519U,
            .sampctrl_address = 520U,
            .cal_address = 524U,
            .ch0res_address = 528U,
            .cmp_address = 536U,
            .muxctrl_address = 513U,
            .ch_intctrl_address = 514U,
            .vector_index = 34U,
        }}},

    .ac_xmega_count = 1U,
    .acs_xmega = {{
        {
            .ctrla_address = 900U,
            .ctrlb_address = 901U,
            .winctrl_address = 902U,
            .status_address = 903U,
            .ac0ctrl_address = 896U,
            .ac1ctrl_address = 897U,
            .ac0mux_address = 898U,
            .ac1mux_address = 899U,
            .vector_index = 31U,
        }}},

    .tc_count = 3U,
    .timers_tc = {{
        {
            .ctrla_address = 2048U,
            .ctrlb_address = 2049U,
            .ctrlc_address = 2050U,
            .ctrld_address = 2051U,
            .ctrle_address = 2052U,
            .intctrla_address = 2054U,
            .intctrlb_address = 2055U,
            .ctrlgclr_address = 2056U,
            .ctrlgset_address = 2057U,
            .intflags_address = 2060U,
            .temp_address = 2063U,
            .cnt_address = 2080U,
            .period_address = 2086U,
            .cca_address = 2088U,
            .ccb_address = 2090U,
            .ccc_address = 2092U,
            .ccd_address = 2094U,
            .perbuf_address = 2102U,
            .ccabuf_address = 2104U,
            .ccbbuf_address = 2106U,
            .cccbuf_address = 2108U,
            .ccdbuf_address = 2110U,
            .ovf_vector_index = 12U,
            .err_vector_index = 13U,
            .cca_vector_index = 14U,
            .ccb_vector_index = 15U,
            .ccc_vector_index = 16U,
            .ccd_vector_index = 17U,
            .port_letter = 67U,
        },
        {
            .ctrla_address = 2112U,
            .ctrlb_address = 2113U,
            .ctrlc_address = 2114U,
            .ctrld_address = 2115U,
            .ctrle_address = 2116U,
            .intctrla_address = 2118U,
            .intctrlb_address = 2119U,
            .ctrlgclr_address = 2120U,
            .ctrlgset_address = 2121U,
            .intflags_address = 2124U,
            .temp_address = 2127U,
            .cnt_address = 2144U,
            .period_address = 2150U,
            .cca_address = 2152U,
            .ccb_address = 2154U,
            .perbuf_address = 2166U,
            .ccabuf_address = 2168U,
            .ccbbuf_address = 2170U,
            .ovf_vector_index = 18U,
            .err_vector_index = 19U,
            .cca_vector_index = 20U,
            .ccb_vector_index = 21U,
            .port_letter = 67U,
        },
        {
            .ctrla_address = 2368U,
            .ctrlb_address = 2369U,
            .ctrlc_address = 2370U,
            .ctrld_address = 2371U,
            .ctrle_address = 2372U,
            .intctrla_address = 2374U,
            .intctrlb_address = 2375U,
            .ctrlgclr_address = 2376U,
            .ctrlgset_address = 2377U,
            .intflags_address = 2380U,
            .temp_address = 2383U,
            .cnt_address = 2400U,
            .period_address = 2406U,
            .cca_address = 2408U,
            .ccb_address = 2410U,
            .perbuf_address = 2422U,
            .ccabuf_address = 2424U,
            .ccbbuf_address = 2426U,
            .ovf_vector_index = 36U,
            .err_vector_index = 37U,
            .cca_vector_index = 38U,
            .ccb_vector_index = 39U,
            .port_letter = 68U,
        }
    }},

    .rtc_count = 1U,
    .timers_rtc = {{
        {
            .ctrla_address = 1024U,
            .status_address = 1025U,
            .intctrl_address = 1026U,
            .intflags_address = 1027U,
            .temp_address = 1028U,
            .calib_address = 1030U,
            .cnt_address = 1032U,
            .per_address = 1034U,
            .cmp_address = 1036U,
            .ovf_vector_index = 7U,
            .pit_vector_index = 8U,
        }}},

    .evsys = {
        .strobe_address = 400U,
        .channels_address = 384U,
        .users_address = 392U,
        .channel_count = 8U,
    },

    .clkctrl = {
        .ctrla_address = 64U,
    },
    .slpctrl = { .ctrla_address = 72U },
    .rstctrl = { .rstfr_address = 120U },
    .syscfg = { .reves_address = 144U },

    .uart8x_count = 2U,
    .uarts8x = {{
        {
            .ctrla_address = 2242U,
            .ctrlb_address = 2243U,
            .ctrlc_address = 2244U,
            .ctrld_address = 2245U,
            .status_address = 2241U,
            .baud_address = 2246U,
            .rxdata_address = 2240U,
            .txdata_address = 2240U,
            .rx_vector_index = 23U,
            .tx_vector_index = 25U,
            .dre_vector_index = 24U,
        },
        {
            .ctrla_address = 2498U,
            .ctrlb_address = 2499U,
            .ctrlc_address = 2500U,
            .ctrld_address = 2501U,
            .status_address = 2497U,
            .baud_address = 2502U,
            .rxdata_address = 2496U,
            .txdata_address = 2496U,
            .rx_vector_index = 40U,
            .tx_vector_index = 42U,
            .dre_vector_index = 41U,
        }
    }},

    .nvm_ctrl_count = 1U,
    .nvm_ctrls = {{
        {
            .ctrla_address = 459U,
            .status_address = 463U,
            .intctrl_address = 461U,
        }}},

    .cpu_int_count = 1U,
    .cpu_ints = {{
        {
            .ctrla_address = 162U,
            .status_address = 160U,
            .lvl0pri_address = 161U,
        }}},

    .spi8x_count = 1U,
    .spis8x = {{
        {
            .ctrla_address = 2272U,
            .ctrlb_address = 2276U,
            .intctrl_address = 2273U,
            .intflags_address = 2274U,
            .data_address = 2275U,
            .vector_index = 22U,
        }
    }},

    .twi8x_count = 1U,
    .twis8x = {{
        {
            .mctrla_address = 1152U,
            .mctrlb_address = 1153U,
            .mstatus_address = 1154U,
            .mbaud_address = 1156U,
            .maddr_address = 1155U,
            .mdata_address = 1156U,
            .sctrla_address = 1152U,
            .sctrlb_address = 1153U,
            .sstatus_address = 1154U,
            .saddr_address = 1155U,
            .sdata_address = 1156U,
            .saddrmask_address = 1157U,
        }
    }},

    .wdt8x_count = 1U,
    .wdts8x = {{
        {
            .ctrla_address = 128U,
            .winctrla_address = 129U,
            .status_address = 130U,
        }}},

    .crc8x_count = 1U,
    .crcs8x = {{
        {
            .ctrla_address = 208U,
            .status_address = 209U,
            .data_address = 211U,
            .checksum_address = 212U,
        }}},

    .xmega_dac_count = 1U,
    .xmega_dacs = {{
        {
            .ctrla_address = 768U,
            .ctrlb_address = 769U,
            .ctrlc_address = 770U,
            .evctrl_address = 771U,
            .status_address = 773U,
            .ch0gaincal_address = 776U,
            .ch0offsetcal_address = 777U,
            .ch1gaincal_address = 778U,
            .ch1offsetcal_address = 779U,
            .ch0data_address = 792U,
            .ch1data_address = 794U,
        }
    }},

    .ircom_count = 1U,
    .ircoms = {{
        {
            .ctrl_address = 2296U,
            .txplctrl_address = 2297U,
            .rxplctrl_address = 2298U,
        }}},
    .fuse_address = 0x0000U,
    .lockbit_address = 0x0000U,
    .signature_address = 0x0000U,
    .signature = { 0x1EU, 0x93U, 0x41U },

    .port_count = 4U,
    .ports = {{
        {
            .name = "PORTA",
            .pin_address = 0x0608U,
            .ddr_address = 0x0600U,
            .port_address = 0x0604U,
            .dirset_address = 0x0601U,
            .dirclr_address = 0x0602U,
            .dirtgl_address = 0x0603U,
            .outset_address = 0x0605U,
            .outclr_address = 0x0606U,
            .outtgl_address = 0x0607U,
            .pin_ctrl_base = 0x0610U,
            .intflags_address = 0x060CU,
            .vport_base = 0x0010U,
            .vector_index = 30U,
            .remap_address = 0x060EU,
        },
        {
            .name = "PORTC",
            .pin_address = 0x0648U,
            .ddr_address = 0x0640U,
            .port_address = 0x0644U,
            .dirset_address = 0x0641U,
            .dirclr_address = 0x0642U,
            .dirtgl_address = 0x0643U,
            .outset_address = 0x0645U,
            .outclr_address = 0x0646U,
            .outtgl_address = 0x0647U,
            .pin_ctrl_base = 0x0650U,
            .intflags_address = 0x064CU,
            .vport_base = 0x0014U,
            .vector_index = 9U,
            .remap_address = 0x064EU,
        },
        {
            .name = "PORTD",
            .pin_address = 0x0668U,
            .ddr_address = 0x0660U,
            .port_address = 0x0664U,
            .dirset_address = 0x0661U,
            .dirclr_address = 0x0662U,
            .dirtgl_address = 0x0663U,
            .outset_address = 0x0665U,
            .outclr_address = 0x0666U,
            .outtgl_address = 0x0667U,
            .pin_ctrl_base = 0x0670U,
            .intflags_address = 0x066CU,
            .vport_base = 0x0018U,
            .vector_index = 35U,
            .remap_address = 0x066EU,
        },
        {
            .name = "PORTR",
            .pin_address = 0x07E8U,
            .ddr_address = 0x07E0U,
            .port_address = 0x07E4U,
            .dirset_address = 0x07E1U,
            .dirclr_address = 0x07E2U,
            .dirtgl_address = 0x07E3U,
            .outset_address = 0x07E5U,
            .outclr_address = 0x07E6U,
            .outtgl_address = 0x07E7U,
            .pin_ctrl_base = 0x07F0U,
            .intflags_address = 0x07ECU,
            .vport_base = 0x001CU,
            .vector_index = 2U,
            .remap_address = 0x07EEU,
        }
    }},
};

}  // namespace vioavr::core::devices
