#pragma once
#include "vioavr/core/device.hpp"

namespace vioavr::core::devices {

inline constexpr DeviceDescriptor atxmega16a4u {
    .name = "ATxmega16A4U",
    .flash_words = 12288U,
    .sram_bytes = 2048U,
    .sram_start = 0x2000U,
    .eeprom_bytes = 1024U,
    .interrupt_vector_count = 126U,
    .interrupt_vector_size = 4U,
    .flash_page_size = 0x256U,
    .register_file_range = { 0x0000, 0x001F },
    .io_range = { 0x0000, 0x003F },
    .extended_io_range = { 0x0040, 0x0FFF },
    .mapped_eeprom = { 0x1000U, 0x0400U },

    .spl_address = 0x3DU,
    .sph_address = 0x3EU,
    .sreg_address = 0x3FU,
    .rampz_address = 0x3BU,
    .eind_address = 0x3CU,
    .prr_address = 112U,
    .ccp_address = 0x34U,
    .cpu_frequency_hz = 32'000'000U,

    .adc_xmega_count = 1U,
    .adcs_xmega = {{
        {
            .ctrla_address = 512U,
            .ctrlb_address = 513U,
            .refctrl_address = 514U,
            .evctrl_address = 515U,
            .prescaler_address = 516U,
            .intflags_address = 515U,
            .temp_address = 519U,
            .cal_address = 524U,
            .ch0res_address = 528U,
            .cmp_address = 536U,
            .muxctrl_address = 513U,
            .ch_intctrl_address = 514U,
            .vector_index = 71U,
        }}},

    .ac_xmega_count = 1U,
    .acs_xmega = {{
        {
            .ctrla_address = 900U,
            .ctrlb_address = 901U,
            .winctrl_address = 902U,
            .status_address = 903U,
            .ac0ctrl_address = 896U,
            .ac1ctrl_address = 897U,
            .ac0mux_address = 898U,
            .ac1mux_address = 899U,
            .vector_index = 68U,
        }}},

    .tc_count = 5U,
    .timers_tc = {{
        {
            .ctrla_address = 2048U,
            .ctrlb_address = 2049U,
            .ctrlc_address = 2050U,
            .ctrld_address = 2051U,
            .ctrle_address = 2052U,
            .intctrla_address = 2054U,
            .intctrlb_address = 2055U,
            .ctrlfclr_address = 2056U,
            .ctrlfset_address = 2057U,
            .ctrlgclr_address = 2058U,
            .ctrlgset_address = 2059U,
            .intflags_address = 2060U,
            .temp_address = 2063U,
            .cnt_address = 2080U,
            .period_address = 2086U,
            .cca_address = 2088U,
            .ccb_address = 2090U,
            .ccc_address = 2092U,
            .ccd_address = 2094U,
            .perbuf_address = 2102U,
            .ccabuf_address = 2104U,
            .ccbbuf_address = 2106U,
            .cccbuf_address = 2108U,
            .ccdbuf_address = 2110U,
            .ovf_vector_index = 14U,
            .err_vector_index = 15U,
            .cca_vector_index = 16U,
            .ccb_vector_index = 17U,
            .ccc_vector_index = 18U,
            .ccd_vector_index = 19U,
            .port_letter = 67U,
        },
        {
            .ctrla_address = 2112U,
            .ctrlb_address = 2113U,
            .ctrlc_address = 2114U,
            .ctrld_address = 2115U,
            .ctrle_address = 2116U,
            .intctrla_address = 2118U,
            .intctrlb_address = 2119U,
            .ctrlfclr_address = 2120U,
            .ctrlfset_address = 2121U,
            .ctrlgclr_address = 2122U,
            .ctrlgset_address = 2123U,
            .intflags_address = 2124U,
            .temp_address = 2127U,
            .cnt_address = 2144U,
            .period_address = 2150U,
            .cca_address = 2152U,
            .ccb_address = 2154U,
            .perbuf_address = 2166U,
            .ccabuf_address = 2168U,
            .ccbbuf_address = 2170U,
            .ovf_vector_index = 20U,
            .err_vector_index = 21U,
            .cca_vector_index = 22U,
            .ccb_vector_index = 23U,
            .port_letter = 67U,
        },
        {
            .ctrla_address = 2304U,
            .ctrlb_address = 2305U,
            .ctrlc_address = 2306U,
            .ctrld_address = 2307U,
            .ctrle_address = 2308U,
            .intctrla_address = 2310U,
            .intctrlb_address = 2311U,
            .ctrlfclr_address = 2312U,
            .ctrlfset_address = 2313U,
            .ctrlgclr_address = 2314U,
            .ctrlgset_address = 2315U,
            .intflags_address = 2316U,
            .temp_address = 2319U,
            .cnt_address = 2336U,
            .period_address = 2342U,
            .cca_address = 2344U,
            .ccb_address = 2346U,
            .ccc_address = 2348U,
            .ccd_address = 2350U,
            .perbuf_address = 2358U,
            .ccabuf_address = 2360U,
            .ccbbuf_address = 2362U,
            .cccbuf_address = 2364U,
            .ccdbuf_address = 2366U,
            .ovf_vector_index = 77U,
            .err_vector_index = 78U,
            .cca_vector_index = 79U,
            .ccb_vector_index = 80U,
            .ccc_vector_index = 81U,
            .ccd_vector_index = 82U,
            .port_letter = 68U,
        },
        {
            .ctrla_address = 2368U,
            .ctrlb_address = 2369U,
            .ctrlc_address = 2370U,
            .ctrld_address = 2371U,
            .ctrle_address = 2372U,
            .intctrla_address = 2374U,
            .intctrlb_address = 2375U,
            .ctrlfclr_address = 2376U,
            .ctrlfset_address = 2377U,
            .ctrlgclr_address = 2378U,
            .ctrlgset_address = 2379U,
            .intflags_address = 2380U,
            .temp_address = 2383U,
            .cnt_address = 2400U,
            .period_address = 2406U,
            .cca_address = 2408U,
            .ccb_address = 2410U,
            .perbuf_address = 2422U,
            .ccabuf_address = 2424U,
            .ccbbuf_address = 2426U,
            .ovf_vector_index = 83U,
            .err_vector_index = 84U,
            .cca_vector_index = 85U,
            .ccb_vector_index = 86U,
            .port_letter = 68U,
        },
        {
            .ctrla_address = 2560U,
            .ctrlb_address = 2561U,
            .ctrlc_address = 2562U,
            .ctrld_address = 2563U,
            .ctrle_address = 2564U,
            .intctrla_address = 2566U,
            .intctrlb_address = 2567U,
            .ctrlfclr_address = 2568U,
            .ctrlfset_address = 2569U,
            .ctrlgclr_address = 2570U,
            .ctrlgset_address = 2571U,
            .intflags_address = 2572U,
            .temp_address = 2575U,
            .cnt_address = 2592U,
            .period_address = 2598U,
            .cca_address = 2600U,
            .ccb_address = 2602U,
            .ccc_address = 2604U,
            .ccd_address = 2606U,
            .perbuf_address = 2614U,
            .ccabuf_address = 2616U,
            .ccbbuf_address = 2618U,
            .cccbuf_address = 2620U,
            .ccdbuf_address = 2622U,
            .ovf_vector_index = 47U,
            .err_vector_index = 48U,
            .cca_vector_index = 49U,
            .ccb_vector_index = 50U,
            .ccc_vector_index = 51U,
            .ccd_vector_index = 52U,
            .port_letter = 69U,
        }
    }},

    .awex_count = 1U,
    .awexs = {{
        {
            .ctrl_address = 2176U,
            .fdemask_address = 2178U,
            .fdctrl_address = 2179U,
            .status_address = 2180U,
            .dtboth_address = 2182U,
            .dtbothbuf_address = 2183U,
            .dtls_address = 2184U,
            .dths_address = 2185U,
            .dtlsbuf_address = 2186U,
            .dthsbuf_address = 2187U,
            .outoven_address = 2188U,
        }
    }},

    .rtc_count = 1U,
    .timers_rtc = {{
        {
            .ctrla_address = 1024U,
            .status_address = 1025U,
            .intctrl_address = 1026U,
            .intflags_address = 1027U,
            .temp_address = 1028U,
            .cnt_address = 1032U,
            .per_address = 1034U,
            .cmp_address = 1036U,
            .ovf_vector_index = 10U,
            .pit_vector_index = 11U,
        }}},

    .evsys = {
        .strobe_address = 400U,
        .channels_address = 384U,
        .users_address = 392U,
        .channel_count = 8U,
    },

    .clkctrl = {
        .ctrla_address = 64U,
    },
    .slpctrl = { .ctrla_address = 72U },
    .rstctrl = { .rstfr_address = 120U },
    .syscfg = { .reves_address = 144U },

    .uart8x_count = 5U,
    .uarts8x = {{
        {
            .ctrla_address = 2211U,
            .ctrlb_address = 2212U,
            .ctrlc_address = 2213U,
            .status_address = 2209U,
            .baud_address = 2214U,
            .rxdata_address = 2208U,
            .txdata_address = 2208U,
            .rx_vector_index = 25U,
            .tx_vector_index = 27U,
            .dre_vector_index = 26U,
        },
        {
            .ctrla_address = 2227U,
            .ctrlb_address = 2228U,
            .ctrlc_address = 2229U,
            .status_address = 2225U,
            .baud_address = 2230U,
            .rxdata_address = 2224U,
            .txdata_address = 2224U,
            .rx_vector_index = 28U,
            .tx_vector_index = 30U,
            .dre_vector_index = 29U,
        },
        {
            .ctrla_address = 2467U,
            .ctrlb_address = 2468U,
            .ctrlc_address = 2469U,
            .status_address = 2465U,
            .baud_address = 2470U,
            .rxdata_address = 2464U,
            .txdata_address = 2464U,
            .rx_vector_index = 88U,
            .tx_vector_index = 90U,
            .dre_vector_index = 89U,
        },
        {
            .ctrla_address = 2483U,
            .ctrlb_address = 2484U,
            .ctrlc_address = 2485U,
            .status_address = 2481U,
            .baud_address = 2486U,
            .rxdata_address = 2480U,
            .txdata_address = 2480U,
            .rx_vector_index = 91U,
            .tx_vector_index = 93U,
            .dre_vector_index = 92U,
        },
        {
            .ctrla_address = 2723U,
            .ctrlb_address = 2724U,
            .ctrlc_address = 2725U,
            .status_address = 2721U,
            .baud_address = 2726U,
            .rxdata_address = 2720U,
            .txdata_address = 2720U,
            .rx_vector_index = 58U,
            .tx_vector_index = 60U,
            .dre_vector_index = 59U,
        }
    }},

    .nvm_ctrl_count = 1U,
    .nvm_ctrls = {{
        {
            .ctrla_address = 459U,
            .status_address = 463U,
            .intctrl_address = 461U,
        }}},

    .cpu_int_count = 1U,
    .cpu_ints = {{
        {
            .ctrla_address = 162U,
            .status_address = 160U,
            .lvl0pri_address = 161U,
        }}},

    .spi8x_count = 2U,
    .spis8x = {{
        {
            .ctrla_address = 2240U,
            .intctrl_address = 2241U,
            .intflags_address = 2242U,
            .data_address = 2243U,
            .vector_index = 24U,
        },
        {
            .ctrla_address = 2496U,
            .intctrl_address = 2497U,
            .intflags_address = 2498U,
            .data_address = 2499U,
            .vector_index = 87U,
        }
    }},

    .twi8x_count = 2U,
    .twis8x = {{
        {
            .mctrla_address = 1152U,
            .mctrlb_address = 1153U,
            .mstatus_address = 1154U,
            .mbaud_address = 1156U,
            .maddr_address = 1155U,
            .mdata_address = 1156U,
            .sctrla_address = 1152U,
            .sctrlb_address = 1153U,
            .sstatus_address = 1154U,
            .saddr_address = 1155U,
            .sdata_address = 1156U,
            .saddrmask_address = 1157U,
        },
        {
            .mctrla_address = 1184U,
            .mctrlb_address = 1185U,
            .mstatus_address = 1186U,
            .mbaud_address = 1188U,
            .maddr_address = 1187U,
            .mdata_address = 1188U,
            .sctrla_address = 1184U,
            .sctrlb_address = 1185U,
            .sstatus_address = 1186U,
            .saddr_address = 1187U,
            .sdata_address = 1188U,
            .saddrmask_address = 1189U,
        }
    }},

    .wdt8x_count = 1U,
    .wdts8x = {{
        {
            .ctrla_address = 128U,
            .winctrla_address = 129U,
            .status_address = 130U,
        }}},

    .crc8x_count = 1U,
    .crcs8x = {{
        {
            .ctrla_address = 208U,
            .status_address = 209U,
            .data_address = 211U,
            .checksum_address = 212U,
        }}},

    .usb8x_count = 1U,
    .usbs8x = {{
        {
            .ctrla_address = 1216U,
            .ctrlb_address = 1217U,
            .busstate_address = 1218U,
            .addr_address = 1219U,
            .fifowp_address = 1220U,
            .fiforp_address = 1221U,
            .epptr_address = 1222U,
            .intctrla_address = 1224U,
            .intctrlb_address = 1225U,
            .intflagsa_address = 1226U,
            .intflagsb_address = 1228U,
            .cal0_address = 1274U,
            .cal1_address = 1275U,
            .gen_vector_index = 126U,
            .bus_vector_index = 125U,
        }}},

    .xmega_dac_count = 1U,
    .xmega_dacs = {{
        {
            .ctrla_address = 800U,
            .ctrlb_address = 801U,
            .ctrlc_address = 802U,
            .evctrl_address = 803U,
            .status_address = 805U,
            .ch0gaincal_address = 808U,
            .ch0offsetcal_address = 809U,
            .ch1gaincal_address = 810U,
            .ch1offsetcal_address = 811U,
            .ch0data_address = 824U,
            .ch1data_address = 826U,
        }
    }},

    .ircom_count = 1U,
    .ircoms = {{
        {
            .ctrl_address = 2296U,
            .txplctrl_address = 2297U,
            .rxplctrl_address = 2298U,
        }}},

    .dma_count = 1U,
    .dmas = {{
        {
            .ctrla_address = 256U,
            .status_address = 260U,
            .intflags_address = 259U,
        }}},
    .fuse_address = 0x0000U,
    .lockbit_address = 0x0000U,
    .signature_address = 0x0000U,
    .signature = { 0x1EU, 0x94U, 0x41U },

    .port_count = 6U,
    .ports = {{
        {
            .name = "PORTA",
            .pin_address = 0x0608U,
            .ddr_address = 0x0600U,
            .port_address = 0x0604U,
            .dirset_address = 0x0601U,
            .dirclr_address = 0x0602U,
            .dirtgl_address = 0x0603U,
            .outset_address = 0x0605U,
            .outclr_address = 0x0606U,
            .outtgl_address = 0x0607U,
            .pin_ctrl_base = 0x0610U,
            .intflags_address = 0x060CU,
            .vport_base = 0x0010U,
            .vector_index = 66U,
            .remap_address = 0x060EU,
        },
        {
            .name = "PORTB",
            .pin_address = 0x0628U,
            .ddr_address = 0x0620U,
            .port_address = 0x0624U,
            .dirset_address = 0x0621U,
            .dirclr_address = 0x0622U,
            .dirtgl_address = 0x0623U,
            .outset_address = 0x0625U,
            .outclr_address = 0x0626U,
            .outtgl_address = 0x0627U,
            .pin_ctrl_base = 0x0630U,
            .intflags_address = 0x062CU,
            .vport_base = 0x0014U,
            .vector_index = 34U,
            .remap_address = 0x062EU,
        },
        {
            .name = "PORTC",
            .pin_address = 0x0648U,
            .ddr_address = 0x0640U,
            .port_address = 0x0644U,
            .dirset_address = 0x0641U,
            .dirclr_address = 0x0642U,
            .dirtgl_address = 0x0643U,
            .outset_address = 0x0645U,
            .outclr_address = 0x0646U,
            .outtgl_address = 0x0647U,
            .pin_ctrl_base = 0x0650U,
            .intflags_address = 0x064CU,
            .vport_base = 0x0018U,
            .vector_index = 2U,
            .remap_address = 0x064EU,
        },
        {
            .name = "PORTD",
            .pin_address = 0x0668U,
            .ddr_address = 0x0660U,
            .port_address = 0x0664U,
            .dirset_address = 0x0661U,
            .dirclr_address = 0x0662U,
            .dirtgl_address = 0x0663U,
            .outset_address = 0x0665U,
            .outclr_address = 0x0666U,
            .outtgl_address = 0x0667U,
            .pin_ctrl_base = 0x0670U,
            .intflags_address = 0x066CU,
            .vport_base = 0x001CU,
            .vector_index = 64U,
            .remap_address = 0x066EU,
        },
        {
            .name = "PORTE",
            .pin_address = 0x0688U,
            .ddr_address = 0x0680U,
            .port_address = 0x0684U,
            .dirset_address = 0x0681U,
            .dirclr_address = 0x0682U,
            .dirtgl_address = 0x0683U,
            .outset_address = 0x0685U,
            .outclr_address = 0x0686U,
            .outtgl_address = 0x0687U,
            .pin_ctrl_base = 0x0690U,
            .intflags_address = 0x068CU,
            .vector_index = 43U,
            .remap_address = 0x068EU,
        },
        {
            .name = "PORTR",
            .pin_address = 0x07E8U,
            .ddr_address = 0x07E0U,
            .port_address = 0x07E4U,
            .dirset_address = 0x07E1U,
            .dirclr_address = 0x07E2U,
            .dirtgl_address = 0x07E3U,
            .outset_address = 0x07E5U,
            .outclr_address = 0x07E6U,
            .outtgl_address = 0x07E7U,
            .pin_ctrl_base = 0x07F0U,
            .intflags_address = 0x07ECU,
            .vector_index = 4U,
            .remap_address = 0x07EEU,
        }
    }},
};

}  // namespace vioavr::core::devices
