#!/usr/bin/env bash
# Copy authoritative ngspice test circuits from the build directory (generated by
# vioavr_viospice_ngspice_all_devices_test) to this scratch directory for manual
# inspection with 'vioavr_oscope --cir <chip>_cosim.cir'.
#
# Usage: ./gen_all.sh
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$(cd "$DIR"/../../build && pwd)"
COSIM_DIR="$BUILD_DIR/cosim_tests"

if [ ! -d "$COSIM_DIR" ]; then
    echo "ERROR: $COSIM_DIR not found. Run the co-sim test first:"
    echo "  ctest --test-dir $BUILD_DIR -R vioavr_viospice_ngspice_all_devices_test"
    exit 1
fi

echo "Copying circuits from $COSIM_DIR to $DIR"
count=0
for d in "$COSIM_DIR"/*/; do
    chip="$(basename "$d")"
    cir="$d/${chip}_cosim.cir"
    if [ -f "$cir" ]; then
        cp "$cir" "$DIR/${chip}_cosim.cir"
        ((count++))
    fi
done

echo "Copied $count circuits."
echo ""
echo "View with oscilloscope:"
echo "  ./build/oscope/vioavr_oscope --cir scratch/ngspice_device_tests/<chip>_cosim.cir"